services:
  server:
    image: ghcr.io/hollow_frenk/mangayomi-sync-server
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MODE=prod
      - DATABASE_URI=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}
      - DB_DIALECT=mysql
      - CORS_ORIGIN_URL=${CORS_ORIGIN_URL} # Imposta CORS per accettare solo richieste dal Tailscale IP
    depends_on:
      database:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}

  database:
    image: mysql/mysql-server:9.2.0-oraclelinux9 # Changed to use Oracle Linux 9 based image
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 1s
      retries: 15
    volumes:
      - database-data:/var/lib/mysql

volumes:
  database-data:
